file_handle = open('/home/nvidia/siyuan-workspace/faster-rcnn.pytorch/test_net_inference_time_distribution.txt', 'a')
file_handle.seek(0)
file_handle.truncate()
file_handle.write('total base rpn roi_pooling classification regression final_nms \n')
file_handle.close()
file_rpn = open('/home/nvidia/siyuan-workspace/faster-rcnn.pytorch/rpn_inference_time_distribution.txt', 'a')
file_rpn.seek(0)
file_rpn.truncate()
file_rpn.write('total convolution get_classification_scores get_bounding_boxes get_proposal \n')
file_rpn.close()
file_prop_layer = open('/home/nvidia/siyuan-workspace/faster-rcnn.pytorch/proposal_layer_time_distribution.txt', 'a')
file_prop_layer.seek(0)
file_prop_layer.truncate()
file_prop_layer.write('total transform get_proposal sort generate_output before_nms nms after_nms')
file_prop_layer.close()